### ISSUE TITLE
您好，我对贵团队的这篇文章很感兴趣，可以提供一下生成pkl数据处理代码吗，谢谢！

### ISSUE THREAD

**Issue by qingyi3** [tsinghua-fib-lab/Graph-Denoising-SocialRec#2]

**Comment by LDY911** [comment]
你好，我想问一下你知道dataset里的user_visited_dict.pkl文件是什么文件吗，我原以为这个文件里的两个字典是验证集和测试集的数据对应的user购买字典，但是里面的购买记录与验证集和测试集不一样，不过同一个user，在字典中和在验证集中的购买item总数是一样的，这个字典是专门从正样本中采集的和验证集长度一致的字典吗，可以这样理解吗

**Comment by QuanYuhan** [comment]
@LDY911  你说的应该是user_item_dict.pkl这个文件，这个文件里面的dict中的key是uid，value是一个index，对应的是这个用户在val/test数组中，这个用户对应的样本的索引值，例如假设dict[0] = {25}，那么一定有val[25]这一条用户与物品交互样本中的uid=0，这是为了在计算metric的时候加速。

@qingyi3 可以的，我们会尽快更新。

**Comment by QuanYuhan** [comment]
@qingyi3 已更新
