### ISSUE TITLE
baseline

### ISSUE THREAD

**Issue by merry-bat** [tsinghua-fib-lab/Graph-Denoising-SocialRec#3]
作者你好！我看文中采用lightgcn等模型作为基线，附加去噪方法，但是我通读代码并没有发现基线这块代码，请问这块代码是在哪里？

**Comment by QuanYuhan** [comment]
你好：
        对于lightgcn，Neuralsparse等基线方法，它们的原文中均提供了开源代码，我们没有进行更多修改，请直接参考它们的开源代码即可。
