### ISSUE TITLE
实验

### ISSUE THREAD

**Issue by merry-bat** [tsinghua-fib-lab/Graph-Denoising-SocialRec#4]
老师你好，请教一下您提出的这个方法如何运用到已有模型中？如lightgcn模型，文章中将方法加入基线模型中得到结果，您提供的代码是不是不包括基线模型，

**Comment by QuanYuhan** [comment]
你好
        lightGCN仅作为对比基准，不涉及与文中方法结合。
        对于Diffnet++和MHCN，具体为先通过文中方法训练模型，获得去噪后的社交网络，然后运行Diffnet++和MHCN，获得推荐结果。去噪过程和推荐模型解耦，且这两个算法代码都已开源，因此请直接参考相关开源即可。

**Comment by merry-bat** [comment]
好的谢谢作者！我还有一个问题就是关于数据处理这块生成visited_and_mask_matrix_30.pkl这个文件的代码可以提供一下吗？

**Comment by merry-bat** [comment]
老师你好！谢谢您的解答，我还有一个问题就是关于数据处理生成visited_and_mask_matrix_30.pkl这个文件的代码可以提供一下吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tsinghua-fib-lab/Graph-Denoising-SocialRec"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月14日(星期五) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tsinghua-fib-lab/Graph-Denoising-SocialRec] 实验 (Issue #4)





 
你好
 lightGCN仅作为对比基准，不涉及与文中方法结合。
 对于Diffnet++和MHCN，具体为先通过文中方法训练模型，获得去噪后的社交网络，然后运行Diffnet++和MHCN，获得推荐结果。去噪过程和推荐模型解耦，且这两个算法代码都已开源，因此请直接参考相关开源即可。

**Comment by QuanYuhan** [comment]
已更新

> 好的谢谢作者！我还有一个问题就是关于数据处理这块生成visited_and_mask_matrix_30.pkl这个文件的代码可以提供一下吗？

**Comment by merry-bat** [comment]
谢谢！
